// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/18/2025, 5:10:12 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/istiak.mahmod/Desktop/Github/nuxt-demo-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/istiak.mahmod/Desktop/Github/nuxt-demo-app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/istiak.mahmod/Desktop/Github/nuxt-demo-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/istiak.mahmod/Desktop/Github/nuxt-demo-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/istiak.mahmod/Desktop/Github/nuxt-demo-app/plugins/**/*.{js,ts,mjs}","/Users/istiak.mahmod/Desktop/Github/nuxt-demo-app/composables/**/*.{js,ts,mjs}","/Users/istiak.mahmod/Desktop/Github/nuxt-demo-app/utils/**/*.{js,ts,mjs}","/Users/istiak.mahmod/Desktop/Github/nuxt-demo-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/istiak.mahmod/Desktop/Github/nuxt-demo-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/istiak.mahmod/Desktop/Github/nuxt-demo-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/istiak.mahmod/Desktop/Github/nuxt-demo-app/app.config.{js,ts,mjs}","/Users/istiak.mahmod/Desktop/Github/nuxt-demo-app/app/spa-loading-template.html"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;